CREATE TABLE kitoltott (
    ref_szam VARCHAR(30) PRIMARY KEY,
    datum DATE NOT NULL,
    dbszam TINYINT,
    fejl_terv BOOLEAN,
    cikk_cime VARCHAR(200) NOT NULL,
    alairas TINYINT,
    naptar TINYINT,
    akadaly TINYINT,
    tagol TINYINT,
    nyelvtan TINYINT,
    utalas TINYINT,
    cimke_minoseg TINYINT,
    cimke_mennyiseg TINYINT,
    cimke_relev TINYINT,
    kategorizal TINYINT,
    sablon_kovet TINYINT,
    minoseg_vege TINYINT,
    elkeszul_ido TINYINT,
    wordpress_idozit TINYINT,
    relevans_idosav TINYINT,
    relevans_tartalom TINYINT,
    elore_irt TINYINT,
    hatarido_vege TINYINT,
    fejlod_minoseg TINYINT,
    hiba_javit TINYINT,
    fejlod_vege TINYINT,
    krit BOOLEAN,
    vege TINYINT,
    no_krit TINYINT,
    kovetelmeny VARCHAR(150),
    megjegyzes TEXT
);